# POST  http://localhost:8000/api/user/login
# content-type: application/json

# {
#   "email": "test4@test.com",
#   "password": "test44"
# }

# POST  http://localhost:8000/mailer
# content-type: application/json

# {
#   "email": "kristilaing@gmail.com",
#   "message": "Muahahaa"
# }

# PUT  http://localhost:8000/api/user/reset-password
# content-type: application/json

# {
#   "email": "test4@test.com",
#   "password": "test4",
#   "newPassword": "test44"
# }

GET http://localhost:8000/api/user/account-activation/5d4567df-ad5b-4771-8cfc-91f7fac12eaa
content-type: application/json

# POST  http://localhost:8000/api/user/signup
# content-type: application/json

# {
#   "email": "kristilaing@gmail.com",
#   "password": "test5"
# }

