# POST  http://localhost:8000/api/user/login
# content-type: application/json

# {
#   "email": "test4@test.com",
#   "password": "test44"
# }

POST  http://localhost:8000/mailer
content-type: application/json

{
  "email": "kristilaing@gmail.com",
  "message": "Muahahaa"
}

# PUT  http://localhost:8000/api/user/reset-password
# content-type: application/json

# {
#   "email": "test4@test.com",
#   "password": "test4",
#   "newPassword": "test44"
# }


# POST  http://localhost:8000/api/user/signup
# content-type: application/json

# {
#   "email": "test4@test.com",
#   "password": "test4"
# }

